openapi: "3.0.1"
info:
  title: Основные отчёты
  version: reports
tags:
  - name: Основные отчёты
    description: ''
servers:
  - url: https://statistics-api.wildberries.ru
security:
  - HeaderApiKey: []
paths:
  /api/v1/supplier/incomes:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      deprecated: true
      x-readonly-method: true
      x-category: statistics
      security:
        - HeaderApiKey: []
      summary: Поставки
      description: |
        Данный метод устарел. Он будет удалён [11 марта](https://dev.wildberries.ru/release-notes?id=431)
      tags:
        - Основные отчёты
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
          required: true
          description: |
            Дата и время последнего изменения по поставке. <br>
            Дата в формате RFC3339. Можно передать дату или дату со временем.
            Время можно указывать с точностью до [секунд](./api-information#tag/Vvedenie/Limity-zaprosov) или миллисекунд. <br>
            Время передаётся в часовом поясе Москва (UTC+3).
            <br>Примеры:
              - `2019-06-20`
              - `2019-06-20T23:59:59`
              - `2019-06-20T00:00:00.12345`
              - `2017-03-25T00:00:00`
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '_schemas.yaml#/components/schemas/IncomesItem'
              example:
                - incomeId: 12345
                  number: ''
                  date: '2022-05-08T00:00:54'
                  lastChangeDate: '2022-05-08T00:44:15.5'
                  supplierArticle: ABCDEF
                  techSize: '0'
                  barcode: '2000328074123'
                  quantity: 3
                  totalPrice: 0
                  dateClose: '2022-05-08T00:00:00'
                  warehouseName: Подольск
                  nmId: 1234567
                  status: Принято
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics'
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics2'
              examples:
                DateFromFieldRequired:
                  $ref: '_schemas.yaml#/components/examples/DateFromFieldRequired'
                DateFromValueNotValidated:
                  $ref: '_schemas.yaml#/components/examples/DateFromValueNotValidated'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
  /api/v1/supplier/stocks:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: statistics
      security:
        - HeaderApiKey: []
      summary: Склады
      description: |
        Метод возвращает остатки товаров на складах WB.

        <div class="description_important">
          Данные этого отчёта могут обновляться с задержкой в несколько часов относительно реальных изменений
        </div>

        Не рекомендуем использовать данный отчёт для оперативного переключения между FBW и FBS логистикой. Для контроля актуальных остатков используйте [Отчёт об остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah).<br><br>

        Сервис не хранит историю наличия товаров на складах, поэтому вы можете получить данные об остатках только в режиме реального времени.<br><br>

        Для одного ответа в системе установлено условное ограничение 60000 строк. Поэтому, чтобы получить все остатки, может потребоваться более, чем один запрос. Во втором и далее запросе в параметре `dateFrom` используйте полное значение поля `lastChangeDate` из последней строки ответа на предыдущий запрос.<br> Если в ответе отдаётся пустой массив `[]`, все остатки уже выгружены.

        <div class="description_limit">
          <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

          | Период | Лимит | Интервал | Всплеск |
          | --- | --- | --- | --- |
          | 1 минута | 1 запрос | 1 минута | 1 запрос |
        </div>
      tags:
        - Основные отчёты
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
          required: true
          description: |
            Дата и время последнего изменения по товару. <br>
            Для получения полного остатка следует указывать максимально раннее значение. <br>
            Например, `2019-06-20` <br>
            Дата в формате RFC3339. Можно передать дату или дату со временем.
            Время можно указывать с точностью до [секунд](./api-information#tag/Vvedenie/Limity-zaprosov) или миллисекунд. <br>
            Время передаётся в часовом поясе Москва (UTC+3).
            <br>Примеры:
              - `2019-06-20`
              - `2019-06-20T23:59:59`
              - `2019-06-20T00:00:00.12345`
              - `2017-03-25T00:00:00`
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '_schemas.yaml#/components/schemas/StocksItem'
              example:
                - lastChangeDate: '2023-07-05T11:13:35'
                  warehouseName: Краснодар
                  supplierArticle: '443284'
                  nmId: 1439871458
                  barcode: '2037401340280'
                  quantity: 33
                  inWayToClient: 1
                  inWayFromClient: 0
                  quantityFull: 34
                  category: Посуда и инвентарь
                  subject: Формы для запекания
                  brand: X
                  techSize: '0'
                  Price: 185
                  Discount: 0
                  isSupply: true
                  isRealization: false
                  SCCode: Tech
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics'
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics2'
              examples:
                DateFromFieldRequired:
                  $ref: '_schemas.yaml#/components/examples/DateFromFieldRequired'
                DateFromValueNotValidated:
                  $ref: '_schemas.yaml#/components/examples/DateFromValueNotValidated'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
  /api/v1/supplier/orders:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: statistics
      security:
        - HeaderApiKey: []
      summary: Заказы
      description: |
        Метод возвращает информацию о заказах.<br>Данные обновляются раз в 30 минут.<br><br>

        1 строка = 1 заказ = 1 сборочное задание = 1 единица товара.<br>Для определения заказа рекомендуем использовать поле `srid`.<br><br>

        Информация о заказе хранится 90 дней с момента оформления.<br><br>

        В ответах могут отсутствовать заказы, по которым не подтверждена оплата. Например, заказы с отложенными платежами или оплатой в рассрочку. При этом, если по таким заказам есть продажи, вы можете получить их с помощью метода [Продажи](/openapi/reports#tag/Osnovnye-otchyoty/paths/~1api~1v1~1supplier~1sales/get).<br>
        Чтобы получить все оформленные заказы, используйте [Ленту заказов](https://seller.wildberries.ru/content-analytics/order-feed) в личном кабинете.

        <div class="description_important">
          Данные этого отчёта являются предварительными и служат для оперативного мониторинга
        </div>

        Для одного ответа на запрос с `flag=0` или без `flag` в системе установлено условное ограничение 80000 строк. Поэтому, чтобы получить все заказы, может потребоваться более, чем один запрос. Во втором и далее запросе в параметре `dateFrom` используйте полное значение поля `lastChangeDate` из последней строки ответа на предыдущий запрос.<br> Если в ответе отдаётся пустой массив `[]`, все заказы уже выгружены.

        <div class="description_limit">
          <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

          | Период | Лимит | Интервал | Всплеск |
          | --- | --- | --- | --- |
          | 1 минута | 1 запрос | 1 минута | 1 запрос |
        </div>
      tags:
        - Основные отчёты
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
          required: true
          description: |
            Дата и время последнего изменения по заказу. <br>
            Дата в формате RFC3339. Можно передать дату или дату со временем.
            Время можно указывать с точностью до [секунд](./api-information#tag/Vvedenie/Limity-zaprosov) или миллисекунд. <br>
            Время передаётся в часовом поясе Москва (UTC+3).
            <br>Примеры:
              - `2019-06-20`
              - `2019-06-20T23:59:59`
              - `2019-06-20T00:00:00.12345`
              - `2017-03-25T00:00:00`
        - $ref: '_schemas.yaml#/components/parameters/flag'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '_schemas.yaml#/components/schemas/OrdersItem'
              example:
                - date: '2022-03-04T18:08:31'
                  lastChangeDate: '2022-03-06T10:11:07'
                  warehouseName: Подольск
                  warehouseType: Склад продавца
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  supplierArticle: '12345'
                  nmId: 1234567
                  barcode: '123453559000'
                  category: Бытовая техника
                  subject: Мультистайлеры
                  brand: Тест
                  techSize: '0'
                  incomeID: 56735459
                  isSupply: false
                  isRealization: true
                  totalPrice: 1887
                  discountPercent: 18
                  spp: 26
                  finishedPrice: 1145
                  priceWithDisc: 1547
                  isCancel: true
                  cancelDate: '2022-03-09T00:00:00'
                  sticker: '926912515'
                  gNumber: '34343462218572569531'
                  srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics'
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics2'
              examples:
                DateFromFieldRequired:
                  $ref: '_schemas.yaml#/components/examples/DateFromFieldRequired'
                DateFromValueNotValidated:
                  $ref: '_schemas.yaml#/components/examples/DateFromValueNotValidated'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
  /api/v1/supplier/sales:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: statistics
      security:
        - HeaderApiKey: []
      summary: Продажи
      description: |
        Метод возвращает информацию о продажах и возвратах.<br>Данные обновляются раз в 30 минут.<br><br>

        1 строка = 1 заказ = 1 сборочное задание = 1 единица товара.<br>Для определения заказа рекомендуем использовать поле `srid`.<br><br>

        Информация о заказе хранится 90 дней с момента оформления.

        <div class="description_important">
          Данные этого отчёта являются предварительными и служат для оперативного мониторинга
        </div>

          - Значения полей `priceWithDisc` и `forPay` рассчитываются по упрощённой логике и могут отличаться от `retail_price_withdisc_rub` и `ppvz_for_pay` соответственно в детализациях к отчётам реализации
          - Поля `finishedPrice`, `priceWithDisc`, `forPay` могут временно иметь значение `0`: данные заполняются асинхронно, актуализируются в течение 24 часов
          - Для заказов, которые оплачены в валюте, отличной от валюты продавца, возможны округления цен из-за конвертации валют

        Для точных финансовых расчётов, сверки и отчётности используйте [детализации к отчётам реализации](/openapi/financial-reports-and-accounting#tag/Finansovye-otchyoty/paths/~1api~1v5~1supplier~1reportDetailByPeriod/get).<br><br>

        Для одного ответа на запрос с `flag=0` или без `flag` в системе установлено условное ограничение 80000 строк. Поэтому, чтобы получить все продажи и возвраты, может потребоваться более, чем один запрос. Во втором и далее запросе в параметре `dateFrom `используйте полное значение поля `lastChangeDate` из последней строки ответа на предыдущий запрос.<br> Если в ответе отдаётся пустой массив `[]`, все продажи и возвраты уже выгружены.

        <div class="description_limit">
          <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

          | Период | Лимит | Интервал | Всплеск |
          | --- | --- | --- | --- |
          | 1 минута | 1 запрос | 1 минута | 1 запрос |
        </div>
      tags:
        - Основные отчёты
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
          required: true
          description: |
            Дата и время последнего изменения по продаже/возврату. <br>
            Дата в формате RFC3339. Можно передать дату или дату со временем.
            Время можно указывать с точностью до [секунд](./api-information#tag/Vvedenie/Limity-zaprosov) или миллисекунд. <br>
            Время передаётся в часовом поясе Москва (UTC+3).
            <br>Примеры:
              - `2019-06-20`
              - `2019-06-20T23:59:59`
              - `2019-06-20T00:00:00.12345`
              - `2017-03-25T00:00:00`
        - $ref: '_schemas.yaml#/components/parameters/flag'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '_schemas.yaml#/components/schemas/SalesItem'
              example:
                - date: '2022-03-04T18:08:31'
                  lastChangeDate: '2022-03-06T10:11:07'
                  warehouseName: Подольск
                  warehouseType: Склад продавца
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  supplierArticle: '12345'
                  nmId: 1234567
                  barcode: '123453559000'
                  category: Бытовая техника
                  subject: Мультистайлеры
                  brand: Тест
                  techSize: '0'
                  incomeID: 56735459
                  isSupply: false
                  isRealization: true
                  totalPrice: 1887
                  discountPercent: 18
                  spp: 20
                  paymentSaleAmount: 93
                  forPay: 1284.01
                  finishedPrice: 1145
                  priceWithDisc: 1547
                  saleID: S9993700024
                  sticker: '926912515'
                  gNumber: '34343462218572569531'
                  srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics'
                  - $ref: '_schemas.yaml#/components/schemas/responseErrorStatistics2'
              examples:
                DateFromFieldRequired:
                  $ref: '_schemas.yaml#/components/examples/DateFromFieldRequired'
                DateFromValueNotValidated:
                  $ref: '_schemas.yaml#/components/examples/DateFromValueNotValidated'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
